using System.Globalization;

namespace SpeakerHop.Services;

public sealed record LanguageOption(string Code, string ResourceKey);

public static class LocalizationService
{
    public const string SystemLanguage = "system";
    public const string Japanese = "ja-JP";
    public const string English = "en-US";
    public const string ChineseSimplified = "zh-CN";
    public const string ChineseTraditional = "zh-TW";
    public const string Korean = "ko-KR";
    public const string German = "de-DE";
    public const string French = "fr-FR";
    public const string Spanish = "es-ES";

    public static IReadOnlyList<LanguageOption> SupportedLanguages { get; } =
    [
        new(SystemLanguage, "language.system"),
        new(Japanese, "language.japanese"),
        new(English, "language.english"),
        new(ChineseSimplified, "language.chineseSimplified"),
        new(ChineseTraditional, "language.chineseTraditional"),
        new(Korean, "language.korean"),
        new(German, "language.german"),
        new(French, "language.french"),
        new(Spanish, "language.spanish")
    ];

    private static readonly Dictionary<string, Dictionary<string, string>> Resources = new(StringComparer.OrdinalIgnoreCase)
    {
        [Japanese] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["nav.devices"] = "デバイス",
            ["nav.shortcuts"] = "ショートカット",
            ["nav.settings"] = "設定",
            ["nav.donation"] = "寄付",
            ["nav.about"] = "情報",
            ["common.on"] = "オン",
            ["common.off"] = "オフ",
            ["common.default"] = "既定",
            ["common.none"] = "なし",
            ["common.unknown"] = "不明",
            ["common.unpackaged"] = "未パッケージ",
            ["devices.title"] = "デバイス",
            ["devices.subtitle"] = "切り替え対象に含める出力デバイスを選択します。タスクトレイアイコンやショートカットで、選択したデバイスを順番に切り替えます。",
            ["devices.notification"] = "デバイス切り替え時に Windows 通知を表示",
            ["devices.notificationDescription"] = "切り替え後の出力先を通知で確認できます。",
            ["devices.notificationsEnabled"] = "デバイス切り替え通知を有効にしました。",
            ["devices.notificationsDisabled"] = "デバイス切り替え通知を無効にしました。",
            ["devices.refresh"] = "更新",
            ["devices.cycleNow"] = "今すぐ切り替え",
            ["devices.saved"] = "サイクル対象デバイスを自動保存しました。",
            ["devices.disconnected"] = "未接続",
            ["devices.lastSeen"] = "最終接続: {0}",
            ["shortcuts.title"] = "ショートカット",
            ["shortcuts.subtitle"] = "デバイスのサイクル切り替え、固定デバイスへの切り替え、音量、ミュートのグローバルショートカットを設定します。",
            ["shortcuts.add"] = "追加",
            ["shortcuts.save"] = "保存して適用",
            ["shortcuts.enable"] = "有効にする",
            ["shortcuts.disable"] = "無効にする",
            ["shortcuts.action"] = "動作を変更",
            ["shortcuts.key"] = "キーを変更",
            ["shortcuts.device"] = "対象を変更",
            ["shortcuts.step"] = "音量幅を変更",
            ["shortcuts.delete"] = "削除",
            ["shortcuts.enabled"] = "有効",
            ["shortcuts.disabled"] = "無効",
            ["shortcuts.actionLabel"] = "動作",
            ["shortcuts.keyLabel"] = "キー",
            ["shortcuts.target"] = "対象",
            ["shortcuts.volumeStep"] = "音量幅",
            ["shortcuts.saved"] = "ショートカットを保存して登録しました。",
            ["shortcuts.unsaved"] = "未保存のショートカット変更があります。保存して適用してください。",
            ["shortcuts.newName"] = "ショートカット {0}",
            ["shortcuts.registrationFailed"] = "保存しましたが、{0} 件のショートカットを登録できませんでした: {1}",
            ["shortcuts.errorCode"] = "エラー",
            ["action.cycleDevice"] = "出力デバイスを順番に切り替え",
            ["action.setDevice"] = "指定した出力デバイスへ切り替え",
            ["action.volumeUp"] = "音量を上げる",
            ["action.volumeDown"] = "音量を下げる",
            ["action.muteToggle"] = "ミュートを切り替え",
            ["audio.getDevicesFailed"] = "音声デバイスを取得できません: {0}",
            ["audio.noCycleDevices"] = "サイクル対象デバイスがありません",
            ["audio.switchFailed"] = "出力先を切り替えできません: {0}",
            ["audio.targetMissing"] = "指定デバイスが見つかりません",
            ["audio.outputTarget"] = "出力先: {0}",
            ["audio.volume"] = "音量: {0}",
            ["audio.volumeChangeFailed"] = "音量を変更できません: {0}",
            ["audio.muted"] = "ミュート",
            ["audio.unmuted"] = "ミュート解除",
            ["audio.muteToggleFailed"] = "ミュートを切り替えできません: {0}",
            ["tray.cycle"] = "次のデバイスへ切り替え",
            ["tray.settings"] = "設定を開く",
            ["tray.exit"] = "終了",
            ["settings.title"] = "設定",
            ["settings.subtitle"] = "表示言語、テーマ、起動時の動作を設定します。",
            ["settings.language"] = "言語",
            ["settings.languageDescription"] = "アプリ内の表示言語です。システム設定では Windows の表示言語に合わせます。",
            ["settings.theme"] = "テーマ",
            ["settings.themeDescription"] = "アプリの表示テーマです。システム設定では Windows のアプリテーマに合わせます。",
            ["settings.applied"] = "設定を保存しました。",
            ["settings.showMainWindowOnStartup"] = "起動時にメインウィンドウを表示",
            ["settings.showMainWindowOnStartupDescription"] = "初回起動後も、SpeakerHop 起動時に設定ウィンドウを開きます。オフの場合はタスクトレイに常駐します。",
            ["settings.startWithWindows"] = "Windows 起動時に開始",
            ["settings.startWithWindowsDescription"] = "サインイン後に SpeakerHop を自動起動します。ストア配布版では Windows のスタートアップ タスクとして登録します。",
            ["settings.startWithWindowsEnabled"] = "Windows 起動時の自動起動を有効にしました。",
            ["settings.startWithWindowsDisabled"] = "Windows 起動時の自動起動を無効にしました。",
            ["settings.startWithWindowsDisabledByUser"] = "Windows 側で自動起動が無効化されています。Windows のスタートアップ アプリ設定を確認してください。",
            ["settings.startWithWindowsDisabledByPolicy"] = "組織またはシステム ポリシーにより自動起動を有効にできません。",
            ["settings.startWithWindowsUnsupported"] = "この実行形式では自動起動の登録を変更できませんでした。",
            ["donation.title"] = "寄付",
            ["donation.subtitle"] = "SpeakerHop が役に立ったら作者への支援をご検討ください。",
            ["donation.message"] = "SpeakerHop はフリーソフトです。寄付は必須ではありませんが、いただけると開発の励みになります。",
            ["donation.buyMeACoffee"] = "Buy Me a Coffee",
            ["donation.openBuyMeACoffee"] = "Buy Me a Coffee で支援する",
            ["language.system"] = "システム設定",
            ["language.japanese"] = "日本語",
            ["language.english"] = "English",
            ["language.chineseSimplified"] = "简体中文",
            ["language.chineseTraditional"] = "繁體中文",
            ["language.korean"] = "한국어",
            ["language.german"] = "Deutsch",
            ["language.french"] = "Français",
            ["language.spanish"] = "Español",
            ["theme.system"] = "システム設定",
            ["theme.light"] = "ライト",
            ["theme.dark"] = "ダーク",
            ["about.title"] = "情報",
            ["about.subtitle"] = "アプリケーション情報とプライバシー情報を確認します。",
            ["about.product"] = "製品",
            ["about.version"] = "バージョン",
            ["about.author"] = "作者",
            ["about.web"] = "Webサイト",
            ["about.privacy"] = "SpeakerHop はローカルで動作し、音声出力デバイス、ホットキー、通知設定をこの PC に保存します。設定情報を外部へ送信しません。",
            ["about.openAuthorSite"] = "作者サイトを開く",
            ["about.exitApplication"] = "アプリケーションを終了",
            ["about.exitApplicationDescription"] = "SpeakerHop を停止し、タスクトレイから削除します。",
            ["device.missing"] = "見つからないデバイス"
        },
        [English] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["nav.devices"] = "Devices",
            ["nav.shortcuts"] = "Shortcuts",
            ["nav.settings"] = "Settings",
            ["nav.donation"] = "Donation",
            ["nav.about"] = "About",
            ["common.on"] = "On",
            ["common.off"] = "Off",
            ["common.default"] = "Default",
            ["common.none"] = "None",
            ["common.unknown"] = "Unknown",
            ["common.unpackaged"] = "Unpackaged",
            ["devices.title"] = "Devices",
            ["devices.subtitle"] = "Choose which output devices are included in the cycle. The tray icon and shortcut move through the selected devices in order.",
            ["devices.notification"] = "Show a Windows notification when the output device changes",
            ["devices.notificationDescription"] = "Confirm the new output device after each switch.",
            ["devices.notificationsEnabled"] = "Device switch notifications enabled.",
            ["devices.notificationsDisabled"] = "Device switch notifications disabled.",
            ["devices.refresh"] = "Refresh",
            ["devices.cycleNow"] = "Cycle now",
            ["devices.saved"] = "Device cycle list saved automatically.",
            ["devices.disconnected"] = "Disconnected",
            ["devices.lastSeen"] = "Last connected: {0}",
            ["shortcuts.title"] = "Shortcuts",
            ["shortcuts.subtitle"] = "Configure global shortcuts for cycling devices, switching to a fixed device, volume, and mute.",
            ["shortcuts.add"] = "Add shortcut",
            ["shortcuts.save"] = "Save and apply",
            ["shortcuts.enable"] = "Enable",
            ["shortcuts.disable"] = "Disable",
            ["shortcuts.action"] = "Change action",
            ["shortcuts.key"] = "Change key",
            ["shortcuts.device"] = "Change target",
            ["shortcuts.step"] = "Change step",
            ["shortcuts.delete"] = "Delete",
            ["shortcuts.enabled"] = "Enabled",
            ["shortcuts.disabled"] = "Disabled",
            ["shortcuts.actionLabel"] = "Action",
            ["shortcuts.keyLabel"] = "Key",
            ["shortcuts.target"] = "Target",
            ["shortcuts.volumeStep"] = "Volume step",
            ["shortcuts.saved"] = "Shortcuts saved and registered.",
            ["shortcuts.unsaved"] = "You have unsaved shortcut changes. Save and apply them to register the shortcuts.",
            ["shortcuts.newName"] = "Shortcut {0}",
            ["shortcuts.registrationFailed"] = "Saved, but {0} shortcut(s) could not be registered: {1}",
            ["shortcuts.errorCode"] = "error",
            ["action.cycleDevice"] = "Cycle through output devices",
            ["action.setDevice"] = "Switch to a fixed output device",
            ["action.volumeUp"] = "Increase volume",
            ["action.volumeDown"] = "Decrease volume",
            ["action.muteToggle"] = "Toggle mute",
            ["audio.getDevicesFailed"] = "Could not get audio devices: {0}",
            ["audio.noCycleDevices"] = "No cycle devices are selected",
            ["audio.switchFailed"] = "Could not switch output device: {0}",
            ["audio.targetMissing"] = "The specified device could not be found",
            ["audio.outputTarget"] = "Output: {0}",
            ["audio.volume"] = "Volume: {0}",
            ["audio.volumeChangeFailed"] = "Could not change volume: {0}",
            ["audio.muted"] = "Muted",
            ["audio.unmuted"] = "Unmuted",
            ["audio.muteToggleFailed"] = "Could not toggle mute: {0}",
            ["tray.cycle"] = "Switch to next device",
            ["tray.settings"] = "Open settings",
            ["tray.exit"] = "Exit",
            ["settings.title"] = "Settings",
            ["settings.subtitle"] = "Set the display language, app theme, and startup behavior.",
            ["settings.language"] = "Language",
            ["settings.languageDescription"] = "The display language used in the app. System follows the Windows display language.",
            ["settings.theme"] = "Theme",
            ["settings.themeDescription"] = "The app display theme. System follows the Windows app theme.",
            ["settings.applied"] = "Settings saved.",
            ["settings.showMainWindowOnStartup"] = "Show main window on startup",
            ["settings.showMainWindowOnStartupDescription"] = "Open the SpeakerHop settings window when the app starts after the first launch. When off, SpeakerHop starts in the tray.",
            ["settings.startWithWindows"] = "Start with Windows",
            ["settings.startWithWindowsDescription"] = "Launch SpeakerHop automatically after sign-in. Store builds use the Windows startup task registration.",
            ["settings.startWithWindowsEnabled"] = "Start with Windows enabled.",
            ["settings.startWithWindowsDisabled"] = "Start with Windows disabled.",
            ["settings.startWithWindowsDisabledByUser"] = "Windows has disabled startup for this app. Check Windows Startup apps settings.",
            ["settings.startWithWindowsDisabledByPolicy"] = "Startup cannot be enabled because it is blocked by system or organization policy.",
            ["settings.startWithWindowsUnsupported"] = "Startup registration could not be changed for this app format.",
            ["donation.title"] = "Donation",
            ["donation.subtitle"] = "Support the author if SpeakerHop is useful to you.",
            ["donation.message"] = "SpeakerHop is free software. Donations are optional, but always appreciated.",
            ["donation.buyMeACoffee"] = "Buy Me a Coffee",
            ["donation.openBuyMeACoffee"] = "Support on Buy Me a Coffee",
            ["language.system"] = "System",
            ["language.japanese"] = "日本語",
            ["language.english"] = "English",
            ["language.chineseSimplified"] = "简体中文",
            ["language.chineseTraditional"] = "繁體中文",
            ["language.korean"] = "한국어",
            ["language.german"] = "Deutsch",
            ["language.french"] = "Français",
            ["language.spanish"] = "Español",
            ["theme.system"] = "System",
            ["theme.light"] = "Light",
            ["theme.dark"] = "Dark",
            ["about.title"] = "About",
            ["about.subtitle"] = "Review application and privacy information.",
            ["about.product"] = "Product",
            ["about.version"] = "Version",
            ["about.author"] = "Author",
            ["about.web"] = "Web",
            ["about.privacy"] = "SpeakerHop runs locally and stores audio output device, hotkey, and notification settings on this PC. It does not send settings outside this device.",
            ["about.openAuthorSite"] = "Open author site",
            ["about.exitApplication"] = "Exit application",
            ["about.exitApplicationDescription"] = "Stop SpeakerHop and remove it from the task tray.",
            ["device.missing"] = "Missing device"
        },
        [ChineseSimplified] = WithEnglishOverrides(
            ("nav.devices", "设备"),
            ("nav.shortcuts", "快捷键"),
            ("nav.settings", "设置"),
            ("nav.donation", "捐赠"),
            ("nav.about", "关于"),
            ("common.on", "开"),
            ("common.off", "关"),
            ("common.default", "默认"),
            ("common.none", "无"),
            ("common.unknown", "未知"),
            ("common.unpackaged", "未打包"),
            ("devices.title", "设备"),
            ("devices.subtitle", "选择要包含在循环切换中的输出设备。任务栏图标和快捷键会按顺序切换所选设备。"),
            ("devices.notification", "切换设备时显示 Windows 通知"),
            ("devices.notificationDescription", "每次切换后确认新的输出设备。"),
            ("devices.notificationsEnabled", "已启用设备切换通知。"),
            ("devices.notificationsDisabled", "已禁用设备切换通知。"),
            ("devices.refresh", "刷新"),
            ("devices.cycleNow", "立即切换"),
            ("devices.saved", "设备循环列表已自动保存。"),
            ("devices.disconnected", "未连接"),
            ("devices.lastSeen", "上次连接: {0}"),
            ("shortcuts.title", "快捷键"),
            ("shortcuts.subtitle", "配置用于循环设备、切换到固定设备、调节音量和静音的全局快捷键。"),
            ("shortcuts.add", "添加快捷键"),
            ("shortcuts.save", "保存并应用"),
            ("shortcuts.enable", "启用"),
            ("shortcuts.disable", "禁用"),
            ("shortcuts.action", "更改操作"),
            ("shortcuts.key", "更改按键"),
            ("shortcuts.device", "更改目标"),
            ("shortcuts.step", "更改步进"),
            ("shortcuts.delete", "删除"),
            ("shortcuts.enabled", "已启用"),
            ("shortcuts.disabled", "已禁用"),
            ("shortcuts.actionLabel", "操作"),
            ("shortcuts.keyLabel", "按键"),
            ("shortcuts.target", "目标"),
            ("shortcuts.volumeStep", "音量步进"),
            ("shortcuts.saved", "快捷键已保存并注册。"),
            ("shortcuts.unsaved", "存在未保存的快捷键更改。请保存并应用以注册快捷键。"),
            ("shortcuts.newName", "快捷键 {0}"),
            ("shortcuts.registrationFailed", "已保存，但有 {0} 个快捷键无法注册: {1}"),
            ("shortcuts.errorCode", "错误"),
            ("action.cycleDevice", "循环切换输出设备"),
            ("action.setDevice", "切换到固定输出设备"),
            ("action.volumeUp", "增大音量"),
            ("action.volumeDown", "减小音量"),
            ("action.muteToggle", "切换静音"),
            ("audio.getDevicesFailed", "无法获取音频设备: {0}"),
            ("audio.noCycleDevices", "没有选择循环设备"),
            ("audio.switchFailed", "无法切换输出设备: {0}"),
            ("audio.targetMissing", "找不到指定设备"),
            ("audio.outputTarget", "输出: {0}"),
            ("audio.volume", "音量: {0}"),
            ("audio.volumeChangeFailed", "无法更改音量: {0}"),
            ("audio.muted", "已静音"),
            ("audio.unmuted", "已取消静音"),
            ("audio.muteToggleFailed", "无法切换静音: {0}"),
            ("tray.cycle", "切换到下一个设备"),
            ("tray.settings", "打开设置"),
            ("tray.exit", "退出"),
            ("settings.title", "设置"),
            ("settings.subtitle", "设置显示语言、应用主题和启动行为。"),
            ("settings.language", "语言"),
            ("settings.languageDescription", "应用内使用的显示语言。系统设置会跟随 Windows 显示语言。"),
            ("settings.theme", "主题"),
            ("settings.themeDescription", "应用显示主题。系统设置会跟随 Windows 应用主题。"),
            ("settings.applied", "设置已保存。"),
            ("settings.showMainWindowOnStartup", "启动时显示主窗口"),
            ("settings.showMainWindowOnStartupDescription", "首次启动后，应用启动时打开 SpeakerHop 设置窗口。关闭时，SpeakerHop 将在任务栏托盘中启动。"),
            ("settings.startWithWindows", "随 Windows 启动"),
            ("settings.startWithWindowsDescription", "登录后自动启动 SpeakerHop。商店版本会使用 Windows 启动任务注册。"),
            ("settings.startWithWindowsEnabled", "已启用随 Windows 启动。"),
            ("settings.startWithWindowsDisabled", "已禁用随 Windows 启动。"),
            ("settings.startWithWindowsDisabledByUser", "Windows 已禁用此应用的启动项。请检查 Windows 启动应用设置。"),
            ("settings.startWithWindowsDisabledByPolicy", "由于系统或组织策略限制，无法启用启动项。"),
            ("settings.startWithWindowsUnsupported", "无法为此应用格式更改启动注册。"),
            ("donation.title", "捐赠"),
            ("donation.subtitle", "如果 SpeakerHop 对你有帮助，请考虑支持作者。"),
            ("donation.message", "SpeakerHop 是免费软件。捐赠不是必需的，但非常感谢。"),
            ("donation.buyMeACoffee", "Buy Me a Coffee"),
            ("donation.openBuyMeACoffee", "在 Buy Me a Coffee 上支持"),
            ("language.system", "系统"),
            ("language.japanese", "日本語"),
            ("language.english", "English"),
            ("language.chineseSimplified", "简体中文"),
            ("language.chineseTraditional", "繁體中文"),
            ("language.korean", "한국어"),
            ("language.german", "Deutsch"),
            ("language.french", "Français"),
            ("language.spanish", "Español"),
            ("theme.system", "系统"),
            ("theme.light", "浅色"),
            ("theme.dark", "深色"),
            ("about.title", "关于"),
            ("about.subtitle", "查看应用和隐私信息。"),
            ("about.product", "产品"),
            ("about.version", "版本"),
            ("about.author", "作者"),
            ("about.web", "网站"),
            ("about.privacy", "SpeakerHop 在本地运行，并将音频输出设备、快捷键和通知设置保存在此电脑上。它不会将设置发送到此设备之外。"),
            ("about.openAuthorSite", "打开作者网站"),
            ("about.exitApplication", "退出应用"),
            ("about.exitApplicationDescription", "停止 SpeakerHop 并将其从任务栏托盘中移除。"),
            ("device.missing", "缺失的设备")),
        [ChineseTraditional] = WithEnglishOverrides(
            ("nav.devices", "裝置"),
            ("nav.shortcuts", "快速鍵"),
            ("nav.settings", "設定"),
            ("nav.donation", "捐贈"),
            ("nav.about", "關於"),
            ("common.on", "開"),
            ("common.off", "關"),
            ("common.default", "預設"),
            ("common.none", "無"),
            ("common.unknown", "未知"),
            ("common.unpackaged", "未封裝"),
            ("devices.title", "裝置"),
            ("devices.subtitle", "選擇要包含在循環切換中的輸出裝置。工作列圖示和快速鍵會依序切換所選裝置。"),
            ("devices.notification", "切換裝置時顯示 Windows 通知"),
            ("devices.notificationDescription", "每次切換後確認新的輸出裝置。"),
            ("devices.notificationsEnabled", "已啟用裝置切換通知。"),
            ("devices.notificationsDisabled", "已停用裝置切換通知。"),
            ("devices.refresh", "重新整理"),
            ("devices.cycleNow", "立即切換"),
            ("devices.saved", "裝置循環清單已自動儲存。"),
            ("devices.disconnected", "未連線"),
            ("devices.lastSeen", "上次連線: {0}"),
            ("shortcuts.title", "快速鍵"),
            ("shortcuts.subtitle", "設定用於循環裝置、切換到固定裝置、音量和靜音的全域快速鍵。"),
            ("shortcuts.add", "新增快速鍵"),
            ("shortcuts.save", "儲存並套用"),
            ("shortcuts.enable", "啟用"),
            ("shortcuts.disable", "停用"),
            ("shortcuts.action", "變更動作"),
            ("shortcuts.key", "變更按鍵"),
            ("shortcuts.device", "變更目標"),
            ("shortcuts.step", "變更步進"),
            ("shortcuts.delete", "刪除"),
            ("shortcuts.enabled", "已啟用"),
            ("shortcuts.disabled", "已停用"),
            ("shortcuts.actionLabel", "動作"),
            ("shortcuts.keyLabel", "按鍵"),
            ("shortcuts.target", "目標"),
            ("shortcuts.volumeStep", "音量步進"),
            ("shortcuts.saved", "快速鍵已儲存並註冊。"),
            ("shortcuts.unsaved", "有未儲存的快速鍵變更。請儲存並套用以註冊快速鍵。"),
            ("shortcuts.newName", "快速鍵 {0}"),
            ("shortcuts.registrationFailed", "已儲存，但有 {0} 個快速鍵無法註冊: {1}"),
            ("shortcuts.errorCode", "錯誤"),
            ("action.cycleDevice", "循環切換輸出裝置"),
            ("action.setDevice", "切換到固定輸出裝置"),
            ("action.volumeUp", "提高音量"),
            ("action.volumeDown", "降低音量"),
            ("action.muteToggle", "切換靜音"),
            ("audio.getDevicesFailed", "無法取得音訊裝置: {0}"),
            ("audio.noCycleDevices", "未選取循環裝置"),
            ("audio.switchFailed", "無法切換輸出裝置: {0}"),
            ("audio.targetMissing", "找不到指定裝置"),
            ("audio.outputTarget", "輸出: {0}"),
            ("audio.volume", "音量: {0}"),
            ("audio.volumeChangeFailed", "無法變更音量: {0}"),
            ("audio.muted", "已靜音"),
            ("audio.unmuted", "已取消靜音"),
            ("audio.muteToggleFailed", "無法切換靜音: {0}"),
            ("tray.cycle", "切換到下一個裝置"),
            ("tray.settings", "開啟設定"),
            ("tray.exit", "結束"),
            ("settings.title", "設定"),
            ("settings.subtitle", "設定顯示語言、應用程式主題和啟動行為。"),
            ("settings.language", "語言"),
            ("settings.languageDescription", "應用程式內使用的顯示語言。系統設定會跟隨 Windows 顯示語言。"),
            ("settings.theme", "主題"),
            ("settings.themeDescription", "應用程式顯示主題。系統設定會跟隨 Windows 應用程式主題。"),
            ("settings.applied", "設定已儲存。"),
            ("settings.showMainWindowOnStartup", "啟動時顯示主視窗"),
            ("settings.showMainWindowOnStartupDescription", "首次啟動後，應用程式啟動時開啟 SpeakerHop 設定視窗。關閉時，SpeakerHop 會在工作列托盤中啟動。"),
            ("settings.startWithWindows", "隨 Windows 啟動"),
            ("settings.startWithWindowsDescription", "登入後自動啟動 SpeakerHop。商店版本會使用 Windows 啟動工作註冊。"),
            ("settings.startWithWindowsEnabled", "已啟用隨 Windows 啟動。"),
            ("settings.startWithWindowsDisabled", "已停用隨 Windows 啟動。"),
            ("settings.startWithWindowsDisabledByUser", "Windows 已停用此應用程式的啟動項。請檢查 Windows 啟動應用程式設定。"),
            ("settings.startWithWindowsDisabledByPolicy", "因系統或組織原則限制，無法啟用啟動項。"),
            ("settings.startWithWindowsUnsupported", "無法為此應用程式格式變更啟動註冊。"),
            ("donation.title", "捐贈"),
            ("donation.subtitle", "如果 SpeakerHop 對你有幫助，請考慮支持作者。"),
            ("donation.message", "SpeakerHop 是免費軟體。捐贈不是必需的，但非常感謝。"),
            ("donation.buyMeACoffee", "Buy Me a Coffee"),
            ("donation.openBuyMeACoffee", "在 Buy Me a Coffee 上支持"),
            ("language.system", "系統"),
            ("language.japanese", "日本語"),
            ("language.english", "English"),
            ("language.chineseSimplified", "简体中文"),
            ("language.chineseTraditional", "繁體中文"),
            ("language.korean", "한국어"),
            ("language.german", "Deutsch"),
            ("language.french", "Français"),
            ("language.spanish", "Español"),
            ("theme.system", "系統"),
            ("theme.light", "淺色"),
            ("theme.dark", "深色"),
            ("about.title", "關於"),
            ("about.subtitle", "查看應用程式和隱私資訊。"),
            ("about.product", "產品"),
            ("about.version", "版本"),
            ("about.author", "作者"),
            ("about.web", "網站"),
            ("about.privacy", "SpeakerHop 在本機執行，並將音訊輸出裝置、快速鍵和通知設定儲存在此電腦上。它不會將設定傳送到此裝置之外。"),
            ("about.openAuthorSite", "開啟作者網站"),
            ("about.exitApplication", "結束應用程式"),
            ("about.exitApplicationDescription", "停止 SpeakerHop 並將其從工作列托盤中移除。"),
            ("device.missing", "遺失的裝置")),
        [Korean] = WithEnglishOverrides(
            ("nav.devices", "장치"),
            ("nav.shortcuts", "바로 가기"),
            ("nav.settings", "설정"),
            ("nav.donation", "후원"),
            ("nav.about", "정보"),
            ("common.on", "켬"),
            ("common.off", "끔"),
            ("common.default", "기본값"),
            ("common.none", "없음"),
            ("common.unknown", "알 수 없음"),
            ("common.unpackaged", "패키지 없음"),
            ("devices.title", "장치"),
            ("devices.subtitle", "순환 전환에 포함할 출력 장치를 선택합니다. 트레이 아이콘과 바로 가기는 선택한 장치를 순서대로 전환합니다."),
            ("devices.notification", "장치 전환 시 Windows 알림 표시"),
            ("devices.notificationDescription", "각 전환 후 새 출력 장치를 확인합니다."),
            ("devices.notificationsEnabled", "장치 전환 알림을 사용하도록 설정했습니다."),
            ("devices.notificationsDisabled", "장치 전환 알림을 사용하지 않도록 설정했습니다."),
            ("devices.refresh", "새로 고침"),
            ("devices.cycleNow", "지금 전환"),
            ("devices.saved", "장치 순환 목록을 자동 저장했습니다."),
            ("devices.disconnected", "연결 안 됨"),
            ("devices.lastSeen", "마지막 연결: {0}"),
            ("shortcuts.title", "바로 가기"),
            ("shortcuts.subtitle", "장치 순환, 고정 장치 전환, 볼륨 및 음소거용 전역 바로 가기를 설정합니다."),
            ("shortcuts.add", "바로 가기 추가"),
            ("shortcuts.save", "저장 및 적용"),
            ("shortcuts.enable", "사용"),
            ("shortcuts.disable", "사용 안 함"),
            ("shortcuts.action", "동작 변경"),
            ("shortcuts.key", "키 변경"),
            ("shortcuts.device", "대상 변경"),
            ("shortcuts.step", "단계 변경"),
            ("shortcuts.delete", "삭제"),
            ("shortcuts.enabled", "사용"),
            ("shortcuts.disabled", "사용 안 함"),
            ("shortcuts.actionLabel", "동작"),
            ("shortcuts.keyLabel", "키"),
            ("shortcuts.target", "대상"),
            ("shortcuts.volumeStep", "볼륨 단계"),
            ("shortcuts.saved", "바로 가기를 저장하고 등록했습니다."),
            ("shortcuts.unsaved", "저장되지 않은 바로 가기 변경 사항이 있습니다. 바로 가기를 등록하려면 저장하고 적용하세요."),
            ("shortcuts.newName", "바로 가기 {0}"),
            ("shortcuts.registrationFailed", "저장했지만 바로 가기 {0}개를 등록할 수 없습니다: {1}"),
            ("shortcuts.errorCode", "오류"),
            ("action.cycleDevice", "출력 장치 순환"),
            ("action.setDevice", "고정 출력 장치로 전환"),
            ("action.volumeUp", "볼륨 높이기"),
            ("action.volumeDown", "볼륨 낮추기"),
            ("action.muteToggle", "음소거 전환"),
            ("audio.getDevicesFailed", "오디오 장치를 가져올 수 없습니다: {0}"),
            ("audio.noCycleDevices", "선택된 순환 장치가 없습니다"),
            ("audio.switchFailed", "출력 장치를 전환할 수 없습니다: {0}"),
            ("audio.targetMissing", "지정한 장치를 찾을 수 없습니다"),
            ("audio.outputTarget", "출력: {0}"),
            ("audio.volume", "볼륨: {0}"),
            ("audio.volumeChangeFailed", "볼륨을 변경할 수 없습니다: {0}"),
            ("audio.muted", "음소거됨"),
            ("audio.unmuted", "음소거 해제됨"),
            ("audio.muteToggleFailed", "음소거를 전환할 수 없습니다: {0}"),
            ("tray.cycle", "다음 장치로 전환"),
            ("tray.settings", "설정 열기"),
            ("tray.exit", "종료"),
            ("settings.title", "설정"),
            ("settings.subtitle", "표시 언어, 앱 테마 및 시작 동작을 설정합니다."),
            ("settings.language", "언어"),
            ("settings.languageDescription", "앱에서 사용할 표시 언어입니다. 시스템 설정은 Windows 표시 언어를 따릅니다."),
            ("settings.theme", "테마"),
            ("settings.themeDescription", "앱 표시 테마입니다. 시스템 설정은 Windows 앱 테마를 따릅니다."),
            ("settings.applied", "설정을 저장했습니다."),
            ("settings.showMainWindowOnStartup", "시작 시 기본 창 표시"),
            ("settings.showMainWindowOnStartupDescription", "첫 실행 후 앱이 시작될 때 SpeakerHop 설정 창을 엽니다. 끄면 SpeakerHop이 트레이에서 시작됩니다."),
            ("settings.startWithWindows", "Windows와 함께 시작"),
            ("settings.startWithWindowsDescription", "로그인 후 SpeakerHop을 자동으로 시작합니다. 스토어 빌드는 Windows 시작 작업 등록을 사용합니다."),
            ("settings.startWithWindowsEnabled", "Windows와 함께 시작을 사용하도록 설정했습니다."),
            ("settings.startWithWindowsDisabled", "Windows와 함께 시작을 사용하지 않도록 설정했습니다."),
            ("settings.startWithWindowsDisabledByUser", "Windows에서 이 앱의 시작을 사용하지 않도록 설정했습니다. Windows 시작 앱 설정을 확인하세요."),
            ("settings.startWithWindowsDisabledByPolicy", "시스템 또는 조직 정책에 의해 차단되어 시작을 사용할 수 없습니다."),
            ("settings.startWithWindowsUnsupported", "이 앱 형식에서는 시작 등록을 변경할 수 없습니다."),
            ("donation.title", "후원"),
            ("donation.subtitle", "SpeakerHop이 유용하다면 작성자를 지원해 주세요."),
            ("donation.message", "SpeakerHop은 무료 소프트웨어입니다. 후원은 선택 사항이지만 큰 도움이 됩니다."),
            ("donation.buyMeACoffee", "Buy Me a Coffee"),
            ("donation.openBuyMeACoffee", "Buy Me a Coffee에서 후원"),
            ("language.system", "시스템"),
            ("language.japanese", "日本語"),
            ("language.english", "English"),
            ("language.chineseSimplified", "简体中文"),
            ("language.chineseTraditional", "繁體中文"),
            ("language.korean", "한국어"),
            ("language.german", "Deutsch"),
            ("language.french", "Français"),
            ("language.spanish", "Español"),
            ("theme.system", "시스템"),
            ("theme.light", "밝게"),
            ("theme.dark", "어둡게"),
            ("about.title", "정보"),
            ("about.subtitle", "애플리케이션 및 개인정보 정보를 확인합니다."),
            ("about.product", "제품"),
            ("about.version", "버전"),
            ("about.author", "작성자"),
            ("about.web", "웹"),
            ("about.privacy", "SpeakerHop은 로컬에서 실행되며 오디오 출력 장치, 바로 가기 및 알림 설정을 이 PC에 저장합니다. 설정을 이 장치 밖으로 보내지 않습니다."),
            ("about.openAuthorSite", "작성자 사이트 열기"),
            ("about.exitApplication", "애플리케이션 종료"),
            ("about.exitApplicationDescription", "SpeakerHop을 중지하고 작업 표시줄 트레이에서 제거합니다."),
            ("device.missing", "누락된 장치")),
        [German] = WithEnglishOverrides(
            ("nav.devices", "Geräte"),
            ("nav.shortcuts", "Tastenkürzel"),
            ("nav.settings", "Einstellungen"),
            ("nav.donation", "Spenden"),
            ("nav.about", "Info"),
            ("common.on", "Ein"),
            ("common.off", "Aus"),
            ("common.default", "Standard"),
            ("common.none", "Keine"),
            ("common.unknown", "Unbekannt"),
            ("common.unpackaged", "Nicht paketiert"),
            ("devices.title", "Geräte"),
            ("devices.subtitle", "Wählen Sie die Ausgabegeräte aus, die in den Wechselzyklus aufgenommen werden. Taskleistensymbol und Tastenkürzel wechseln der Reihe nach durch die ausgewählten Geräte."),
            ("devices.notification", "Windows-Benachrichtigung beim Gerätewechsel anzeigen"),
            ("devices.notificationDescription", "Bestätigt das neue Ausgabegerät nach jedem Wechsel."),
            ("devices.notificationsEnabled", "Benachrichtigungen beim Gerätewechsel aktiviert."),
            ("devices.notificationsDisabled", "Benachrichtigungen beim Gerätewechsel deaktiviert."),
            ("devices.refresh", "Aktualisieren"),
            ("devices.cycleNow", "Jetzt wechseln"),
            ("devices.saved", "Gerätezyklusliste automatisch gespeichert."),
            ("devices.disconnected", "Getrennt"),
            ("devices.lastSeen", "Zuletzt verbunden: {0}"),
            ("shortcuts.title", "Tastenkürzel"),
            ("shortcuts.subtitle", "Konfigurieren Sie globale Tastenkürzel für Gerätewechsel, feste Geräte, Lautstärke und Stummschaltung."),
            ("shortcuts.add", "Tastenkürzel hinzufügen"),
            ("shortcuts.save", "Speichern und anwenden"),
            ("shortcuts.enable", "Aktivieren"),
            ("shortcuts.disable", "Deaktivieren"),
            ("shortcuts.action", "Aktion ändern"),
            ("shortcuts.key", "Taste ändern"),
            ("shortcuts.device", "Ziel ändern"),
            ("shortcuts.step", "Schritt ändern"),
            ("shortcuts.delete", "Löschen"),
            ("shortcuts.enabled", "Aktiviert"),
            ("shortcuts.disabled", "Deaktiviert"),
            ("shortcuts.actionLabel", "Aktion"),
            ("shortcuts.keyLabel", "Taste"),
            ("shortcuts.target", "Ziel"),
            ("shortcuts.volumeStep", "Lautstärkeschritt"),
            ("shortcuts.saved", "Tastenkürzel gespeichert und registriert."),
            ("shortcuts.unsaved", "Es gibt ungespeicherte Änderungen an Tastenkürzeln. Speichern und anwenden, um sie zu registrieren."),
            ("shortcuts.newName", "Tastenkürzel {0}"),
            ("shortcuts.registrationFailed", "Gespeichert, aber {0} Tastenkürzel konnten nicht registriert werden: {1}"),
            ("shortcuts.errorCode", "Fehler"),
            ("action.cycleDevice", "Ausgabegeräte der Reihe nach wechseln"),
            ("action.setDevice", "Zu festem Ausgabegerät wechseln"),
            ("action.volumeUp", "Lautstärke erhöhen"),
            ("action.volumeDown", "Lautstärke verringern"),
            ("action.muteToggle", "Stummschaltung umschalten"),
            ("audio.getDevicesFailed", "Audiogeräte konnten nicht abgerufen werden: {0}"),
            ("audio.noCycleDevices", "Keine Geräte für den Zyklus ausgewählt"),
            ("audio.switchFailed", "Ausgabegerät konnte nicht gewechselt werden: {0}"),
            ("audio.targetMissing", "Das angegebene Gerät wurde nicht gefunden"),
            ("audio.outputTarget", "Ausgabe: {0}"),
            ("audio.volume", "Lautstärke: {0}"),
            ("audio.volumeChangeFailed", "Lautstärke konnte nicht geändert werden: {0}"),
            ("audio.muted", "Stummgeschaltet"),
            ("audio.unmuted", "Stummschaltung aufgehoben"),
            ("audio.muteToggleFailed", "Stummschaltung konnte nicht umgeschaltet werden: {0}"),
            ("tray.cycle", "Zum nächsten Gerät wechseln"),
            ("tray.settings", "Einstellungen öffnen"),
            ("tray.exit", "Beenden"),
            ("settings.title", "Einstellungen"),
            ("settings.subtitle", "Anzeigesprache, App-Design und Startverhalten festlegen."),
            ("settings.language", "Sprache"),
            ("settings.languageDescription", "Die in der App verwendete Anzeigesprache. System folgt der Windows-Anzeigesprache."),
            ("settings.theme", "Design"),
            ("settings.themeDescription", "Das App-Design. System folgt dem Windows-App-Design."),
            ("settings.applied", "Einstellungen gespeichert."),
            ("settings.showMainWindowOnStartup", "Hauptfenster beim Start anzeigen"),
            ("settings.showMainWindowOnStartupDescription", "Öffnet nach dem ersten Start das SpeakerHop-Einstellungsfenster beim App-Start. Wenn aus, startet SpeakerHop im Infobereich."),
            ("settings.startWithWindows", "Mit Windows starten"),
            ("settings.startWithWindowsDescription", "SpeakerHop nach der Anmeldung automatisch starten. Store-Builds verwenden die Windows-Startaufgabenregistrierung."),
            ("settings.startWithWindowsEnabled", "Start mit Windows aktiviert."),
            ("settings.startWithWindowsDisabled", "Start mit Windows deaktiviert."),
            ("settings.startWithWindowsDisabledByUser", "Windows hat den Start für diese App deaktiviert. Prüfen Sie die Windows-Einstellungen für Start-Apps."),
            ("settings.startWithWindowsDisabledByPolicy", "Der Start kann wegen System- oder Organisationsrichtlinien nicht aktiviert werden."),
            ("settings.startWithWindowsUnsupported", "Die Startregistrierung konnte für dieses App-Format nicht geändert werden."),
            ("donation.title", "Spenden"),
            ("donation.subtitle", "Unterstützen Sie den Autor, wenn SpeakerHop für Sie nützlich ist."),
            ("donation.message", "SpeakerHop ist kostenlose Software. Spenden sind optional, werden aber sehr geschätzt."),
            ("donation.buyMeACoffee", "Buy Me a Coffee"),
            ("donation.openBuyMeACoffee", "Auf Buy Me a Coffee unterstützen"),
            ("language.system", "System"),
            ("language.japanese", "日本語"),
            ("language.english", "English"),
            ("language.chineseSimplified", "简体中文"),
            ("language.chineseTraditional", "繁體中文"),
            ("language.korean", "한국어"),
            ("language.german", "Deutsch"),
            ("language.french", "Français"),
            ("language.spanish", "Español"),
            ("theme.system", "System"),
            ("theme.light", "Hell"),
            ("theme.dark", "Dunkel"),
            ("about.title", "Info"),
            ("about.subtitle", "Anwendungs- und Datenschutzinformationen anzeigen."),
            ("about.product", "Produkt"),
            ("about.version", "Version"),
            ("about.author", "Autor"),
            ("about.web", "Web"),
            ("about.privacy", "SpeakerHop läuft lokal und speichert Audioausgabegeräte, Tastenkürzel und Benachrichtigungseinstellungen auf diesem PC. Es sendet keine Einstellungen außerhalb dieses Geräts."),
            ("about.openAuthorSite", "Autor-Website öffnen"),
            ("about.exitApplication", "Anwendung beenden"),
            ("about.exitApplicationDescription", "SpeakerHop stoppen und aus dem Infobereich entfernen."),
            ("device.missing", "Fehlendes Gerät")),
        [French] = WithEnglishOverrides(
            ("nav.devices", "Appareils"),
            ("nav.shortcuts", "Raccourcis"),
            ("nav.settings", "Paramètres"),
            ("nav.donation", "Don"),
            ("nav.about", "À propos"),
            ("common.on", "Activé"),
            ("common.off", "Désactivé"),
            ("common.default", "Par défaut"),
            ("common.none", "Aucun"),
            ("common.unknown", "Inconnu"),
            ("common.unpackaged", "Non empaqueté"),
            ("devices.title", "Appareils"),
            ("devices.subtitle", "Choisissez les périphériques de sortie inclus dans le cycle. L’icône de la zone de notification et le raccourci passent d’un appareil sélectionné à l’autre dans l’ordre."),
            ("devices.notification", "Afficher une notification Windows lors du changement d’appareil"),
            ("devices.notificationDescription", "Confirme le nouveau périphérique de sortie après chaque changement."),
            ("devices.notificationsEnabled", "Notifications de changement d’appareil activées."),
            ("devices.notificationsDisabled", "Notifications de changement d’appareil désactivées."),
            ("devices.refresh", "Actualiser"),
            ("devices.cycleNow", "Changer maintenant"),
            ("devices.saved", "Liste de cycle des appareils enregistrée automatiquement."),
            ("devices.disconnected", "Déconnecté"),
            ("devices.lastSeen", "Dernière connexion: {0}"),
            ("shortcuts.title", "Raccourcis"),
            ("shortcuts.subtitle", "Configurez des raccourcis globaux pour changer d’appareil, choisir un appareil fixe, régler le volume et couper le son."),
            ("shortcuts.add", "Ajouter un raccourci"),
            ("shortcuts.save", "Enregistrer et appliquer"),
            ("shortcuts.enable", "Activer"),
            ("shortcuts.disable", "Désactiver"),
            ("shortcuts.action", "Modifier l’action"),
            ("shortcuts.key", "Modifier la touche"),
            ("shortcuts.device", "Modifier la cible"),
            ("shortcuts.step", "Modifier le pas"),
            ("shortcuts.delete", "Supprimer"),
            ("shortcuts.enabled", "Activé"),
            ("shortcuts.disabled", "Désactivé"),
            ("shortcuts.actionLabel", "Action"),
            ("shortcuts.keyLabel", "Touche"),
            ("shortcuts.target", "Cible"),
            ("shortcuts.volumeStep", "Pas de volume"),
            ("shortcuts.saved", "Raccourcis enregistrés et inscrits."),
            ("shortcuts.unsaved", "Des modifications de raccourcis ne sont pas enregistrées. Enregistrez et appliquez pour les inscrire."),
            ("shortcuts.newName", "Raccourci {0}"),
            ("shortcuts.registrationFailed", "Enregistré, mais {0} raccourci(s) n’ont pas pu être inscrits: {1}"),
            ("shortcuts.errorCode", "erreur"),
            ("action.cycleDevice", "Faire défiler les périphériques de sortie"),
            ("action.setDevice", "Basculer vers un périphérique de sortie fixe"),
            ("action.volumeUp", "Augmenter le volume"),
            ("action.volumeDown", "Diminuer le volume"),
            ("action.muteToggle", "Activer/désactiver le son"),
            ("audio.getDevicesFailed", "Impossible d’obtenir les périphériques audio: {0}"),
            ("audio.noCycleDevices", "Aucun périphérique de cycle n’est sélectionné"),
            ("audio.switchFailed", "Impossible de changer de périphérique de sortie: {0}"),
            ("audio.targetMissing", "Le périphérique spécifié est introuvable"),
            ("audio.outputTarget", "Sortie: {0}"),
            ("audio.volume", "Volume: {0}"),
            ("audio.volumeChangeFailed", "Impossible de modifier le volume: {0}"),
            ("audio.muted", "Son coupé"),
            ("audio.unmuted", "Son rétabli"),
            ("audio.muteToggleFailed", "Impossible d’activer/désactiver le son: {0}"),
            ("tray.cycle", "Passer au périphérique suivant"),
            ("tray.settings", "Ouvrir les paramètres"),
            ("tray.exit", "Quitter"),
            ("settings.title", "Paramètres"),
            ("settings.subtitle", "Définir la langue d’affichage, le thème et le comportement au démarrage."),
            ("settings.language", "Langue"),
            ("settings.languageDescription", "Langue d’affichage utilisée dans l’application. Système suit la langue d’affichage de Windows."),
            ("settings.theme", "Thème"),
            ("settings.themeDescription", "Thème d’affichage de l’application. Système suit le thème d’application Windows."),
            ("settings.applied", "Paramètres enregistrés."),
            ("settings.showMainWindowOnStartup", "Afficher la fenêtre principale au démarrage"),
            ("settings.showMainWindowOnStartupDescription", "Après le premier lancement, ouvre la fenêtre des paramètres de SpeakerHop au démarrage. Désactivé, SpeakerHop démarre dans la zone de notification."),
            ("settings.startWithWindows", "Démarrer avec Windows"),
            ("settings.startWithWindowsDescription", "Lancer SpeakerHop automatiquement après la connexion. Les versions Store utilisent la tâche de démarrage Windows."),
            ("settings.startWithWindowsEnabled", "Démarrage avec Windows activé."),
            ("settings.startWithWindowsDisabled", "Démarrage avec Windows désactivé."),
            ("settings.startWithWindowsDisabledByUser", "Windows a désactivé le démarrage de cette application. Vérifiez les paramètres des applications de démarrage Windows."),
            ("settings.startWithWindowsDisabledByPolicy", "Le démarrage ne peut pas être activé car il est bloqué par une stratégie système ou d’organisation."),
            ("settings.startWithWindowsUnsupported", "L’inscription au démarrage n’a pas pu être modifiée pour ce format d’application."),
            ("donation.title", "Don"),
            ("donation.subtitle", "Soutenez l’auteur si SpeakerHop vous est utile."),
            ("donation.message", "SpeakerHop est un logiciel gratuit. Les dons sont facultatifs, mais toujours appréciés."),
            ("donation.buyMeACoffee", "Buy Me a Coffee"),
            ("donation.openBuyMeACoffee", "Soutenir sur Buy Me a Coffee"),
            ("language.system", "Système"),
            ("language.japanese", "日本語"),
            ("language.english", "English"),
            ("language.chineseSimplified", "简体中文"),
            ("language.chineseTraditional", "繁體中文"),
            ("language.korean", "한국어"),
            ("language.german", "Deutsch"),
            ("language.french", "Français"),
            ("language.spanish", "Español"),
            ("theme.system", "Système"),
            ("theme.light", "Clair"),
            ("theme.dark", "Sombre"),
            ("about.title", "À propos"),
            ("about.subtitle", "Consulter les informations de l’application et de confidentialité."),
            ("about.product", "Produit"),
            ("about.version", "Version"),
            ("about.author", "Auteur"),
            ("about.web", "Web"),
            ("about.privacy", "SpeakerHop fonctionne localement et stocke les périphériques de sortie audio, les raccourcis et les paramètres de notification sur ce PC. Il n’envoie pas les paramètres hors de cet appareil."),
            ("about.openAuthorSite", "Ouvrir le site de l’auteur"),
            ("about.exitApplication", "Quitter l’application"),
            ("about.exitApplicationDescription", "Arrêter SpeakerHop et le retirer de la zone de notification."),
            ("device.missing", "Appareil manquant")),
        [Spanish] = WithEnglishOverrides(
            ("nav.devices", "Dispositivos"),
            ("nav.shortcuts", "Atajos"),
            ("nav.settings", "Configuración"),
            ("nav.donation", "Donación"),
            ("nav.about", "Acerca de"),
            ("common.on", "Activado"),
            ("common.off", "Desactivado"),
            ("common.default", "Predeterminado"),
            ("common.none", "Ninguno"),
            ("common.unknown", "Desconocido"),
            ("common.unpackaged", "Sin empaquetar"),
            ("devices.title", "Dispositivos"),
            ("devices.subtitle", "Elige qué dispositivos de salida se incluyen en el ciclo. El icono de la bandeja y el atajo recorren los dispositivos seleccionados en orden."),
            ("devices.notification", "Mostrar una notificación de Windows al cambiar el dispositivo"),
            ("devices.notificationDescription", "Confirma el nuevo dispositivo de salida después de cada cambio."),
            ("devices.notificationsEnabled", "Notificaciones de cambio de dispositivo activadas."),
            ("devices.notificationsDisabled", "Notificaciones de cambio de dispositivo desactivadas."),
            ("devices.refresh", "Actualizar"),
            ("devices.cycleNow", "Cambiar ahora"),
            ("devices.saved", "Lista de ciclo de dispositivos guardada automáticamente."),
            ("devices.disconnected", "Desconectado"),
            ("devices.lastSeen", "Última conexión: {0}"),
            ("shortcuts.title", "Atajos"),
            ("shortcuts.subtitle", "Configura atajos globales para cambiar dispositivos, cambiar a un dispositivo fijo, volumen y silencio."),
            ("shortcuts.add", "Agregar atajo"),
            ("shortcuts.save", "Guardar y aplicar"),
            ("shortcuts.enable", "Activar"),
            ("shortcuts.disable", "Desactivar"),
            ("shortcuts.action", "Cambiar acción"),
            ("shortcuts.key", "Cambiar tecla"),
            ("shortcuts.device", "Cambiar destino"),
            ("shortcuts.step", "Cambiar paso"),
            ("shortcuts.delete", "Eliminar"),
            ("shortcuts.enabled", "Activado"),
            ("shortcuts.disabled", "Desactivado"),
            ("shortcuts.actionLabel", "Acción"),
            ("shortcuts.keyLabel", "Tecla"),
            ("shortcuts.target", "Destino"),
            ("shortcuts.volumeStep", "Paso de volumen"),
            ("shortcuts.saved", "Atajos guardados y registrados."),
            ("shortcuts.unsaved", "Hay cambios de atajos sin guardar. Guarda y aplica para registrarlos."),
            ("shortcuts.newName", "Atajo {0}"),
            ("shortcuts.registrationFailed", "Guardado, pero no se pudieron registrar {0} atajo(s): {1}"),
            ("shortcuts.errorCode", "error"),
            ("action.cycleDevice", "Recorrer dispositivos de salida"),
            ("action.setDevice", "Cambiar a un dispositivo de salida fijo"),
            ("action.volumeUp", "Subir volumen"),
            ("action.volumeDown", "Bajar volumen"),
            ("action.muteToggle", "Alternar silencio"),
            ("audio.getDevicesFailed", "No se pudieron obtener los dispositivos de audio: {0}"),
            ("audio.noCycleDevices", "No hay dispositivos de ciclo seleccionados"),
            ("audio.switchFailed", "No se pudo cambiar el dispositivo de salida: {0}"),
            ("audio.targetMissing", "No se encontró el dispositivo especificado"),
            ("audio.outputTarget", "Salida: {0}"),
            ("audio.volume", "Volumen: {0}"),
            ("audio.volumeChangeFailed", "No se pudo cambiar el volumen: {0}"),
            ("audio.muted", "Silenciado"),
            ("audio.unmuted", "Silencio desactivado"),
            ("audio.muteToggleFailed", "No se pudo alternar el silencio: {0}"),
            ("tray.cycle", "Cambiar al siguiente dispositivo"),
            ("tray.settings", "Abrir configuración"),
            ("tray.exit", "Salir"),
            ("settings.title", "Configuración"),
            ("settings.subtitle", "Establece el idioma, el tema y el comportamiento de inicio."),
            ("settings.language", "Idioma"),
            ("settings.languageDescription", "Idioma usado en la aplicación. Sistema sigue el idioma de visualización de Windows."),
            ("settings.theme", "Tema"),
            ("settings.themeDescription", "Tema de la aplicación. Sistema sigue el tema de aplicaciones de Windows."),
            ("settings.applied", "Configuración guardada."),
            ("settings.showMainWindowOnStartup", "Mostrar ventana principal al iniciar"),
            ("settings.showMainWindowOnStartupDescription", "Después del primer inicio, abre la ventana de configuración de SpeakerHop al iniciar la aplicación. Si está desactivado, SpeakerHop inicia en la bandeja."),
            ("settings.startWithWindows", "Iniciar con Windows"),
            ("settings.startWithWindowsDescription", "Inicia SpeakerHop automáticamente después de iniciar sesión. Las compilaciones Store usan el registro de tarea de inicio de Windows."),
            ("settings.startWithWindowsEnabled", "Inicio con Windows activado."),
            ("settings.startWithWindowsDisabled", "Inicio con Windows desactivado."),
            ("settings.startWithWindowsDisabledByUser", "Windows ha desactivado el inicio para esta aplicación. Revisa la configuración de aplicaciones de inicio de Windows."),
            ("settings.startWithWindowsDisabledByPolicy", "No se puede activar el inicio porque está bloqueado por una directiva del sistema o de la organización."),
            ("settings.startWithWindowsUnsupported", "No se pudo cambiar el registro de inicio para este formato de aplicación."),
            ("donation.title", "Donación"),
            ("donation.subtitle", "Apoya al autor si SpeakerHop te resulta útil."),
            ("donation.message", "SpeakerHop es software gratuito. Las donaciones son opcionales, pero siempre se agradecen."),
            ("donation.buyMeACoffee", "Buy Me a Coffee"),
            ("donation.openBuyMeACoffee", "Apoyar en Buy Me a Coffee"),
            ("language.system", "Sistema"),
            ("language.japanese", "日本語"),
            ("language.english", "English"),
            ("language.chineseSimplified", "简体中文"),
            ("language.chineseTraditional", "繁體中文"),
            ("language.korean", "한국어"),
            ("language.german", "Deutsch"),
            ("language.french", "Français"),
            ("language.spanish", "Español"),
            ("theme.system", "Sistema"),
            ("theme.light", "Claro"),
            ("theme.dark", "Oscuro"),
            ("about.title", "Acerca de"),
            ("about.subtitle", "Revisa la información de la aplicación y de privacidad."),
            ("about.product", "Producto"),
            ("about.version", "Versión"),
            ("about.author", "Autor"),
            ("about.web", "Web"),
            ("about.privacy", "SpeakerHop se ejecuta localmente y guarda los dispositivos de salida de audio, atajos y configuración de notificaciones en este PC. No envía la configuración fuera de este dispositivo."),
            ("about.openAuthorSite", "Abrir sitio del autor"),
            ("about.exitApplication", "Salir de la aplicación"),
            ("about.exitApplicationDescription", "Detener SpeakerHop y quitarlo de la bandeja."),
            ("device.missing", "Dispositivo faltante"))
    };

    private static Dictionary<string, string> WithEnglishOverrides(params (string Key, string Value)[] overrides)
    {
        var resource = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var (key, value) in overrides)
        {
            resource[key] = value;
        }

        return resource;
    }

    public static string Text(string key, string? configuredLanguage)
    {
        var language = ResolveLanguage(configuredLanguage);
        if (Resources.TryGetValue(language, out var resource) && resource.TryGetValue(key, out var value))
        {
            return value;
        }

        if (Resources[English].TryGetValue(key, out var fallback))
        {
            return fallback;
        }

        return key;
    }

    public static string ResolveLanguage(string? configuredLanguage)
    {
        var configured = SupportedLanguages
            .Skip(1)
            .FirstOrDefault(language => string.Equals(configuredLanguage, language.Code, StringComparison.OrdinalIgnoreCase));
        if (configured is not null)
        {
            return configured.Code;
        }

        var culture = CultureInfo.CurrentUICulture.Name;
        if (culture.StartsWith("zh-Hant", StringComparison.OrdinalIgnoreCase) ||
            culture.StartsWith("zh-TW", StringComparison.OrdinalIgnoreCase) ||
            culture.StartsWith("zh-HK", StringComparison.OrdinalIgnoreCase) ||
            culture.StartsWith("zh-MO", StringComparison.OrdinalIgnoreCase))
        {
            return ChineseTraditional;
        }

        if (culture.StartsWith("zh", StringComparison.OrdinalIgnoreCase))
        {
            return ChineseSimplified;
        }

        var exact = SupportedLanguages
            .Skip(1)
            .FirstOrDefault(language => string.Equals(culture, language.Code, StringComparison.OrdinalIgnoreCase));
        if (exact is not null)
        {
            return exact.Code;
        }

        var prefix = culture.Split('-')[0];
        var matched = SupportedLanguages
            .Skip(1)
            .FirstOrDefault(language => language.Code.StartsWith(prefix + "-", StringComparison.OrdinalIgnoreCase));
        return matched?.Code ?? English;
    }
}
